version: "2"
linters:
  enable:
    - embeddedstructfieldcheck
    - exhaustive
    - funcorder
    - gocheckcompilerdirectives
    - iface
    - modernize
    - nilerr
    - nlreturn
    - nolintlint
    - perfsprint
    - prealloc
    - predeclared
    - recvcheck
    - tagalign
    - testifylint
    - thelper
    - usestdlibvars
    - whitespace
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
  settings:
    exhaustive:
      default-signifies-exhaustive: true
formatters:
  enable:
    - gofumpt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
