name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install ebiten build dependencies
      run: |
        sudo apt install gcc libc6-dev libgl1-mesa-dev libxcursor-dev \
                         libxi-dev libxinerama-dev libxrandr-dev \
                         libxxf86vm-dev libasound2-dev pkg-config

    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      run: make build

    - name: Unit tests
      run: make test

    - name: Blargg cpu_instrs tests
      run: make cpu_instrs
