name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      DISPLAY: ':99.0'

    steps:
    - name: Install ebiten build dependencies
      run: |
        sudo apt install gcc libc6-dev libgl1-mesa-dev libxcursor-dev \
                         libxi-dev libxinerama-dev libxrandr-dev \
                         libxxf86vm-dev libasound2-dev pkg-config

    - name: Run Xvfb for ebitin
      run: |
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

    - uses: actions/checkout@v7
      with:
        submodules: true

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
          go-version: '1.26'

    - name: Build
      run: make build

    - name: Unit tests
      run: make test

    - name: Blargg cpu_instrs tests
      run: make cpu_instrs

    - name: DMG Acid2
      run: make dmg_acid2

    - name: DMG Acid2 (CGB in DMG mode)
      run: make dmg_acid2_cgb

    - name: CGB Acid2
      run: make cgb_acid2
