name: golangci-lint
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Install ebiten build dependencies
        run: |
          sudo apt install gcc libc6-dev libgl1-mesa-dev libxcursor-dev \
                          libxi-dev libxinerama-dev libxrandr-dev \
                          libxxf86vm-dev libasound2-dev pkg-config

      - uses: actions/checkout@v3
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1.6
